---
title: "Data Operations for NYC Taxicab"
author: "Patrick Frenett"
date: "June 23 2016"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

****

## Reverse geocoding NYC `long`/`lat` to zip codes

* Import geojson file to QGIS
    + For this to be done, the file must first be loaded to pgAdmin which will read the json file and then create a geometry column so it can be added/manipulated by PostGIS. A connection between the two pieces of software will have to be made.

* Import point data to pgAdmin
    + Create a new table and specify the columns of the point data (including `long`/`lat`)
    + `
COPY table FROM 'file\path.csv' CSV HEADER;`
    
* Create `location` and `zip` columns
    + `location` should be saved as public.geometry and `zip` should be a character string of length 5
    
* Populate `location` so that it will work with PostGIS
    + `UPDATE data SET location = ST_SetSRID(ST_MakePoint(longitude, latitude),4326)`
    + 4326 is the code for WGS 84, the global reference system used in GPS navigation
    
* Populate `zip` using PostGIS
    + `UPDATE data SET zip = zip_codes.postalcode FROM zip_codes WHERE ST_Within(data.location, zip_codes.geom)`
    
* Export data to .csv file from pgAdmin
    + `COPY data TO 'file_location' DELIMITER ',' CSV HEADER`
    
****

## Updated code for above.

* Create table with correct columns.

`COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-01.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-02.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-03.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-04.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-05.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-06.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-07.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-08.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-09.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-10.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-11.csv' CSV HEADER;
COPY data_2009 FROM 'C:\Users\pfrenett19\Desktop\NYC_taxi\data\data_2009\yellow_tripdata_2009-12.csv' CSV HEADER;

ALTER TABLE data_2009 ADD pickup_location geometry;
ALTER TABLE data_2009 ADD dropoff_location geometry;
ALTER TABLE data_2009 ADD pickup_zip CHAR(5);
ALTER TABLE data_2009 ADD dropoff_zip CHAR(5);

UPDATE data_2009 SET pickup_location = ST_SetSRID(ST_MakePoint(pickup_longitude, pickup_latitude),4326);
UPDATE data_2009 SET dropoff_location = ST_SetSRID(ST_MakePoint(dropoff_longitude, dropoff_latitude),4326);

UPDATE data_2009 SET pickup_zip = zip_codes.postalcode FROM zip_codes WHERE ST_Within(data_2009.pickup_location, zip_codes.geom)
UPDATE data_2009 SET dropoff_zip = zip_codes.postalcode FROM zip_codes WHERE ST_Within(data_2009.dropoff_location, zip_codes.geom)`











